version: "3.8"

services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  oidc-test-client:
    image: ghcr.io/betagouv/moncomptepro-test-client
    ports:
      - "3001:3000"
    environment:
      # default env var can be found at https://github.com/betagouv/moncomptepro-test-client/blob/master/.env
      HOST: http://localhost:3001
      MCP_CLIENT_ID: client_id
      MCP_PROVIDER: http://localhost:3000/

volumes:
  db-data:
