collections:
  - name: https://github.com/etalab/api-infrastructure.git
    type: git
    version: master

roles:
  - name: thefinn93.letsencrypt
  - name: geerlingguy.nodejs
  - name: geerlingguy.certbot
