version: "3.8"

include:
  - path: ../../docker-compose.yml

services:
  moncomptepro-legacy-client:
    depends_on:
      - moncomptepro
    image: ghcr.io/betagouv/moncomptepro-test-client
    labels:
      - traefik.enable=true
      - traefik.http.routers.moncomptepro-legacy-client.rule=Host(`moncomptepro-legacy-client.localhost`)
      - traefik.http.services.moncomptepro-legacy-client.loadbalancer.server.port=80
    environment:
      SITE_TITLE: moncomptepro-legacy-client
      PORT: 80
      HOST: http://moncomptepro-legacy-client.localhost
      MCP_CLIENT_ID: legacy_client_id
      MCP_CLIENT_SECRET: legacy_client_secret
      MCP_PROVIDER: http://app.moncomptepro.localhost/
      MCP_SCOPES: openid email profile phone organizations
      STYLESHEET_URL: ""
    networks:
      default:
        aliases:
          - moncomptepro-legacy-client.localhost

  moncomptepro-standard-client:
    depends_on:
      - moncomptepro
    image: ghcr.io/betagouv/moncomptepro-test-client
    labels:
      - traefik.enable=true
      - traefik.http.routers.moncomptepro-standard-client.rule=Host(`moncomptepro-standard-client.localhost`)
      - traefik.http.services.moncomptepro-standard-client.loadbalancer.server.port=80
    environment:
      SITE_TITLE: moncomptepro-standard-client
      PORT: 80
      HOST: http://moncomptepro-standard-client.localhost
      MCP_CLIENT_ID: standard_client_id
      MCP_CLIENT_SECRET: standard_client_secret
      MCP_PROVIDER: http://app.moncomptepro.localhost/
      MCP_SCOPES: openid email profile organization
      STYLESHEET_URL: ""
    networks:
      default:
        aliases:
          - moncomptepro-standard-client.localhost
